/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class elvis_JNI_HelloWorld */

#ifndef _Included_elvis_JNI_HelloWorld
#define _Included_elvis_JNI_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     elvis_JNI_HelloWorld
 * Method:    sayHello
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_elvis_JNI_HelloWorld_sayHello
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
